### ISSUE TITLE
error when call bplapply

### ISSUE THREAD

**Issue by RuixiangLiu01** [Bioconductor/BiocParallel#114] opened 2020-04-14 10:55 UTC
Dose anyone meet this error "error in mcexit(0l) :write error, closing pipe to the master" when calling the function bplapply?I found this error will "kill" one process when it appears,thanks

**Comment by mtmorgan** [comment] 2020-04-14 12:57
Can you provide a minimal reproducible example, e.g.,

```
result = BiocParallel::bplapply(1:4, sqrt, BPPARAM = BiocParallel::MulticoreParam(2))
```

and include the output of `sessionInfo()`? 

This should be run in a new R session without additional attached or loaded packages. For instance I have (obviously not reproducing the error...)

```
$ R --vanilla
> res = BiocParallel::bplapply(1:4, sqrt, BPPARAM = BiocParallel::MulticoreParam(2))
> sessionInfo()
R version 4.0.0 alpha (2020-04-07 r78168)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /Users/ma38727/bin/R-4-0-branch/lib/libRblas.dylib
LAPACK: /Users/ma38727/bin/R-4-0-branch/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.0      parallel_4.0.0      BiocParallel_1.21.2

**Comment by RuixiangLiu01** [comment] 2020-04-14 14:56
> Can you provide a minimal reproducible example, e.g.,
> 
> ```
> result = BiocParallel::bplapply(1:4, sqrt, BPPARAM = BiocParallel::MulticoreParam(2))
> ```
> 
> and include the output of `sessionInfo()`?
> 
> This should be run in a new R session without additional attached or loaded packages. For instance I have (obviously not reproducing the error...)
> 
> ```
> $ R --vanilla
> > res = BiocParallel::bplapply(1:4, sqrt, BPPARAM = BiocParallel::MulticoreParam(2))
> > sessionInfo()
> R version 4.0.0 alpha (2020-04-07 r78168)
> Platform: x86_64-apple-darwin17.7.0 (64-bit)
> Running under: macOS High Sierra 10.13.6
> 
> Matrix products: default
> BLAS:   /Users/ma38727/bin/R-4-0-branch/lib/libRblas.dylib
> LAPACK: /Users/ma38727/bin/R-4-0-branch/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.0      parallel_4.0.0      BiocParallel_1.21.2
> ```

thanks for your reply,my code is here:
`res = bplapply(clusters, findmarkers, BPPARAM = MulticoreParam(5))`
and the sessioninfo is:
`> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/local/R/R3.6/lib64/R/lib/libRblas.so
LAPACK: /usr/local/R/R3.6/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] RColorBrewer_1.1-2          pheatmap_1.0.12
 [3] reshape2_1.4.3              dplyr_0.8.5
 [5] ggplot2_3.3.0               stringr_1.4.0
 [7] Matrix_1.2-17               MAST_1.12.0
 [9] SingleCellExperiment_1.8.0  SummarizedExperiment_1.16.1
[11] DelayedArray_0.12.2         BiocParallel_1.20.1
[13] matrixStats_0.56.0          Biobase_2.46.0
[15] GenomicRanges_1.38.0        GenomeInfoDb_1.22.0
[17] IRanges_2.20.2              S4Vectors_0.24.3
[19] BiocGenerics_0.32.0         future_1.16.0
[21] Seurat_3.1.4

loaded via a namespace (and not attached):
 [1] TH.data_1.0-10         Rtsne_0.15             colorspace_1.4-1
 [4] ggridges_0.5.2         XVector_0.26.0         leiden_0.3.3
 [7] listenv_0.8.0          npsurv_0.4-0           ggrepel_0.8.2
[10] mvtnorm_1.1-0          codetools_0.2-16       splines_3.6.0
[13] mnormt_1.5-6           lsei_1.2-0             TFisher_0.2.0
[16] jsonlite_1.6.1         ica_1.0-2              cluster_2.0.8
[19] png_0.1-7              uwot_0.1.8             sctransform_0.2.1
[22] compiler_3.6.0         httr_1.4.1             assertthat_0.2.1
[25] lazyeval_0.2.2         htmltools_0.4.0        tools_3.6.0
[28] rsvd_1.0.3             igraph_1.2.5           gtable_0.3.0
[31] glue_1.3.2             GenomeInfoDbData_1.2.2 RANN_2.6.1
[34] rappdirs_0.3.1         Rcpp_1.0.4             vctrs_0.2.4
[37] multtest_2.42.0        gdata_2.18.0           ape_5.3
[40] nlme_3.1-139           gbRd_0.4-11            lmtest_0.9-37
[43] globals_0.12.5         lifecycle_0.2.0        irlba_2.3.3
[46] gtools_3.8.1           MASS_7.3-51.4          zlibbioc_1.32.0
[49] zoo_1.8-7              scales_1.1.0           sandwich_2.5-1
[52] reticulate_1.15        pbapply_1.4-2          gridExtra_2.3
[55] stringi_1.4.6          mutoss_0.1-12          plotrix_3.7-7
[58] caTools_1.18.0         bibtex_0.4.2.2         Rdpack_0.11-1
[61] rlang_0.4.5            pkgconfig_2.0.3        bitops_1.0-6
[64] lattice_0.20-38        ROCR_1.0-7             purrr_0.3.3
[67] patchwork_1.0.0        htmlwidgets_1.5.1      cowplot_1.0.0
[70] tidyselect_1.0.0       RcppAnnoy_0.0.16       plyr_1.8.6
[73] magrittr_1.5           R6_2.4.1               gplots_3.0.3
[76] multcomp_1.4-13        withr_2.1.2            pillar_1.4.3
[79] sn_1.6-1               fitdistrplus_1.0-14    abind_1.4-5
[82] survival_2.44-1.1      RCurl_1.98-1.1         tibble_2.1.3
[85] future.apply_1.4.0     tsne_0.1-3             crayon_1.3.4
[88] KernSmooth_2.23-15     plotly_4.9.2           grid_3.6.0
[91] data.table_1.12.8      metap_1.3              digest_0.6.25
[94] tidyr_1.0.2            numDeriv_2016.8-1.1    munsell_0.5.0
[97] viridisLite_0.3.0
`

**Comment by mtmorgan** [comment] 2020-04-14 15:07
Unfortunately your example is not reproducible!

```
> res = bplapply(clusters, findmarkers, BPPARAM = MulticoreParam(5))
Error in bplapply(clusters, findmarkers, BPPARAM = MulticoreParam(5)) :
  object 'clusters' not found
```

Please help me to help you!

**Comment by RuixiangLiu01** [comment] 2020-04-14 15:22
> Unfortunately your example is not reproducible!
> 
> ```
> > res = bplapply(clusters, findmarkers, BPPARAM = MulticoreParam(5))
> Error in bplapply(clusters, findmarkers, BPPARAM = MulticoreParam(5)) :
>   object 'clusters' not found
> ```
> 
> Please help me to help you!
`clusters = 0:33
findmarkers = function(cluster){
df = Seurat::FindMarkers(dataset, ident.1 = cluster, test.use = 'MAST', only.pos = T)
df$cluster = rep(cluster, nrow(df)
return(df)}
res = bplapply(clusters,  findmarkers,  BPPARAM = MulticoreParam(5))`
that's my full code, but the "dataset" in function "findmarkers" is a large Seurat object so I can not put it here.Anyway,that's the way I use bplapply,and get the error.Sorry for my implicit reply,thank u.

**Comment by mtmorgan** [comment] 2020-04-14 15:43
Can you reproduce this with a dataset that is available in the Seurat package, or somewhere else that is publicly available? Worst case, are you willing to share the object with me privately? I can't fix the problem if I can't reproduce it.

**Comment by RuixiangLiu01** [comment] 2020-04-14 15:51
> Can you reproduce this with a dataset that is available in the Seurat package, or somewhere else that is publicly available? Worst case, are you willing to share the object with me privately? I can't fix the problem if I can't reproduce it.

I remember there's a small pbmc dataset in seurat official website,u can find it and try my code...I must sleep now,sorry

**Comment by mtmorgan** [comment] 2020-04-14 16:05
I won't find it because I don't know what you're talking about, but please get some sleep and update this issue when ready.

**Comment by HenrikBengtsson** [comment] 2020-04-14 16:15
FYI, Seurat has  built-in support for parallelization - no need to run your own outside, cf. https://satijalab.org/seurat/v3.1/future_vignette.html

**Comment by RuixiangLiu01** [comment] 2020-04-15 01:19
> FYI, Seurat has built-in support for parallelization - no need to run your own outside, cf. https://satijalab.org/seurat/v3.1/future_vignette.html

Yes,I notice that vignette,but the problem is that when I set `test.use = 'MAST'`,it dosen't work parallel,but now I found the function `future.apply::future_lapply` can sovle my problem,thank u

**Comment by HenrikBengtsson** [comment] 2020-04-15 01:24
Check with the Seurat folks - there could be a valid reason for why they don't support parallel processing in that case.

**Comment by RuixiangLiu01** [comment] 2020-04-15 01:25
> FYI, Seurat has built-in support for parallelization - no need to run your own outside, cf. https://satijalab.org/seurat/v3.1/future_vignette.html

OH MY GOD!I just noticed u r or maybe your team is the author of future and future.apply!Thanks a lot Professor!Let me be your fans!!!

**Comment by mtmorgan** [comment] 2020-04-15 23:59
I'd like to help but without a reproducible example I can't. So I'll close the issue but if you do have a chance to come up with a reproducible example please post here and I will investigate.

**Closed by mtmorgan** 2020-04-15 23:59 UTC

**Comment by HenrikBengtsson** [comment] 2020-04-16 00:26
> OH MY GOD!I just noticed u r or maybe your team is the author of future and future.apply!Thanks a lot Professor!Let me be your fans!!!

Thanks - but please note that my work stands on the work of many others in the R community.  You can pay it forward by trying to help others in the R community who struggle.  Also, please try to provide minimal reproducible examples, as @mtmorgan asked for, when you ask for help so that others can help you.  Help the helper help you.


> error in mcexit(0l) :write error, closing pipe to the master

This error message indicates that something pretty bad happened in one of the _forked_ processes ("workers").  You run _forked_ parallel processing because you are using the 'MulticoreParam' backend.  You will also find _forked_ processing when you use `parallel::mclapply()` that comes with R, or the `plan(multicore)` backend when you use the future framework.  It is important to understand that these alternative parallelization frameworks share the same pros and cons.  In other words, switch to `plan(multicore)` is unlikely to fix the underlying problem that caused your MulticoreParam worker to crash.
