### ISSUE TITLE
BiocParallel errors: first remote error: Error in model.frame.default

### ISSUE THREAD

**Issue by TPlatek** [Bioconductor/BiocParallel#261] opened 2024-09-04 12:03 UTC
Hello,
I am trying to analyse my methylation DNA EPIC v 2.0 arrays with sesame.
I am using windows version of Sesame.

How to solve BiocParallel errors in SeSaMe using DML calculation?

smry = DML(se1, ~ Sample_Group)
Error: BiocParallel errors
1 remote errors, element index: 1
885161 unevaluated and other errors
first remote error:
Error in model.frame.default(formula = betas[i, ] ~ . + 0, data = as.data.frame(mm), : invalid type (list) for variable 'betas[i, ]'

How to use DoparParam or SnowParam for Windows?

**Comment by mtmorgan** [comment] 2024-09-04 12:31
BiocParallel is reporting an error that occurred remotely. For debugging, you would like to use `SerialParam()`. But it seems like this is already the default -- provide the output of

```r
sessionInfo()
```
and after the error occurs

```r
traceback()
```

Also try before running the code
```{r}
bpregister(SerialParam())
```

Really this is an error that is related to SeSaMe; have you tried asking on the support site https://support.bioconductor.org using the tag `SeSaMe` ?

**Comment by TPlatek** [comment] 2024-09-05 08:46
Thank you for your quickly answer.

My sessionInfo()
``` r
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Europe/Warsaw
tzcode source: internal

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
 [1] lubridate_1.9.3             forcats_1.0.0              
 [3] stringr_1.5.1               dplyr_1.1.4                
 [5] purrr_1.0.2                 readr_2.1.5                
 [7] tidyr_1.3.1                 tibble_3.2.1               
 [9] ggplot2_3.5.1               tidyverse_2.0.0            
[11] sesame_1.22.2               sesameData_1.22.0          
[13] ExperimentHub_2.12.0        AnnotationHub_3.12.0       
[15] BiocFileCache_2.12.0        dbplyr_2.5.0               
[17] SummarizedExperiment_1.34.0 Biobase_2.64.0             
[19] GenomicRanges_1.56.1        GenomeInfoDb_1.40.1        
[21] IRanges_2.38.1              S4Vectors_0.42.1           
[23] BiocGenerics_0.50.0         MatrixGenerics_1.16.0      
[25] matrixStats_1.3.0          

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.1        blob_1.2.4             
 [3] filelock_1.0.3          Biostrings_2.72.1      
 [5] fastmap_1.2.0           timechange_0.3.0       
 [7] lifecycle_1.0.4         KEGGREST_1.44.1        
 [9] RSQLite_2.3.7           magrittr_2.0.3         
[11] compiler_4.4.1          rlang_1.1.4            
[13] tools_4.4.1             utf8_1.2.4             
[15] yaml_2.3.10             S4Arrays_1.4.1         
[17] bit_4.0.5               curl_5.2.2             
[19] DelayedArray_0.30.1     plyr_1.8.9             
[21] RColorBrewer_1.1-3      abind_1.4-5            
[23] BiocParallel_1.38.0     withr_3.0.1            
[25] grid_4.4.1              preprocessCore_1.66.0  
[27] fansi_1.0.6             wheatmap_0.2.0         
[29] colorspace_2.1-1        scales_1.3.0           
[31] cli_3.6.3               crayon_1.5.3           
[33] generics_0.1.3          rstudioapi_0.16.0      
[35] httr_1.4.7              reshape2_1.4.4         
[37] tzdb_0.4.0              DBI_1.2.3              
[39] cachem_1.1.0            zlibbioc_1.50.0        
[41] parallel_4.4.1          AnnotationDbi_1.66.0   
[43] BiocManager_1.30.25     XVector_0.44.0         
[45] vctrs_0.6.5             Matrix_1.7-0           
[47] jsonlite_1.8.8          hms_1.1.3              
[49] bit64_4.0.5             glue_1.7.0             
[51] codetools_0.2-20        stringi_1.8.4          
[53] gtable_0.3.5            BiocVersion_3.19.1     
[55] UCSC.utils_1.0.0        munsell_0.5.1          
[57] pillar_1.9.0            rappdirs_0.3.3         
[59] GenomeInfoDbData_1.2.12 R6_2.5.1               
[61] lattice_0.22-6          png_0.1-8              
[63] memoise_2.0.1           Rcpp_1.0.13            
[65] SparseArray_1.4.8       pkgconfig_2.0.3
```

After the 
``` r
> traceback()

5: stop(.error_bplist(res))
4: .bpinit(manager = manager, X = X, FUN = FUN, ARGS = ARGS, BPPARAM = BPPARAM, 
       BPOPTIONS = BPOPTIONS, BPREDO = BPREDO)
3: BiocParallel::bplapply(seq_len(nrow(betas)), function(i) {
       m0 <- lm(betas[i, ] ~ . + 0, data = as.data.frame(mm))
       sm <- summary(m0)
       sm$cov.unscaled <- NULL
       sm$residuals <- NULL
       sm$terms <- NULL
       sm$Ftest <- do.call(cbind, lapply(mm_holdout, function(mm_) {
           m1 <- lm(betas[i, ] ~ . + 0, data = as.data.frame(mm_))
           anv <- anova(m1, m0)
           c(stat = anv[["F"]][2], pval = anv[["Pr(>F)"]][2])
       }))
       sm
   }, BPPARAM = BPPARAM)
2: BiocParallel::bplapply(seq_len(nrow(betas)), function(i) {
       m0 <- lm(betas[i, ] ~ . + 0, data = as.data.frame(mm))
       sm <- summary(m0)
       sm$cov.unscaled <- NULL
       sm$residuals <- NULL
       sm$terms <- NULL
       sm$Ftest <- do.call(cbind, lapply(mm_holdout, function(mm_) {
           m1 <- lm(betas[i, ] ~ . + 0, data = as.data.frame(mm_))
           anv <- anova(m1, m0)
           c(stat = anv[["F"]][2], pval = anv[["Pr(>F)"]][2])
       }))
       sm
   }, BPPARAM = BPPARAM)
1: DML(betas, ~Sample_Group, meta = meta)
```
And after
``` r
> bpregister(SerialParam())
Error in bpregister(SerialParam()) : could not find function "bpregister"
```

I reported error on SeSaMe GitHub, but I didn't receive any suggestions on how to solve the problem.

I'll try again on the website https://support.bioconductor.org/ using the tag SeSaMe.

**Comment by Jiefei-Wang** [comment] 2024-09-05 10:55
For your case, I guess your `se1` is a `SummarizedExperiment`, so please check the value in `assay(betas0)`. It is expected to be a matrix in `sesame::DML`. Do you have a list of matrices as your assay? That may be the root problem.

**Comment by TPlatek** [comment] 2024-09-05 11:49
Thank you for your quickly answer.
Yes, se1 is a SummarizedExperiment and assay(betas0) is a list of matrices.
I understand that I should go back to creating SE and try to create assay(betas) as a matrix. 
I counted betas in SeSaMe from IDAT files, then saved results as excel. Then I used this excel file as counts:
counts <- read.csv("C:/Wyniki_EPIC_GenomeScan/Dane/R/SE/betas_norm5_3.csv", row.names = 1) 
counts[1:32,]
 and then make SE:
data.se <- SummarizedExperiment(assays = list(counts = counts), colData = coldata, rowData = rowranges)
Is it correct?
Or should I again count betas in SeSaMe in a different way? 
Perhaps that is my problem with format of betas values.
I used 
betas <- cbind(betas of all samples)
 becaue another options as  betas <- do.call(cbind, lapply())
betas <- do.call(cbind, lapply(idat_dir))
 didn't work.

**Comment by Jiefei-Wang** [comment] 2024-09-05 13:07
I think you need to do `SummarizedExperiment(assays = counts, colData = coldata, rowData = rowranges)`. SeSaMe expects a matrix, not a list.

**Comment by TPlatek** [comment] 2024-09-06 11:44
Thank you for your help.  I think that my problem is to transpose or save my betas values data as matrix not as data.frame.
Examples from SeSaMe manual:
m <- matrix(seq(0,1,length.out=9), nrow=3)
rownames(m) <- c("cg00004963_TC21", "cg00004963_TC22", "cg00004747_TC21")
colnames(m) <- c("A","B","C")
betasCollapseToPfx(m)

I don't know how to transpose my values betas to matrix (m).

Using command SummarizedExperiment(assays = counts, colData = coldata, rowData = rowranges) didn't solve the problem because my assay(betas) is still list and the same error appears.

**Comment by Jiefei-Wang** [comment] 2024-09-06 14:41
can you provide a screenshot of your `counts` and the output of `assay(betas)`?  I tried here but I cannot reproduce your issue.

**Comment by TPlatek** [comment] 2024-09-09 10:16
Thank for your comments. According to your suggestions I managed to calculate DML in SeSaMe. I calculated again betas values, these results were given as a large matrix. Then I used this matrix directly to create summarized.experiment. Earlier I unnecessarily saved these betas results as an Excel file and tried to use it for making summarized.experiment.

**Comment by Jiefei-Wang** [comment] 2024-09-09 18:42
Great to hear. I'll go ahead and close this issue.

**Closed as completed by Jiefei-Wang** 2024-09-09 18:42 UTC
